# Generated by Django 4.2.8 on 2024-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureInvokeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_invoke_json', models.JSONField(verbose_name='请求快照参数json')),
                ('status', models.SmallIntegerField(choices=[(1, '待执行'), (2, '已失败')], verbose_name='状态')),
                ('next_retry_time', models.DateTimeField(verbose_name='下一次重试的时间')),
                ('retry_times', models.IntegerField(verbose_name='已经重试的次数')),
                ('max_retry_times', models.IntegerField(verbose_name='最大重试次数')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='执行失败的堆栈')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '本地消息表',
                'db_table': 'secure_invoke_record',
                'indexes': [models.Index(fields=['next_retry_time'], name='secure_invo_next_re_fb36a3_idx')],
            },
        ),
    ]
